package main

type FieldValidation struct {
	IsAlpha        bool `json:"isAlpha"`
	IsAlphaNumeric bool `json:"isAlphaNumeric"`
	Url            bool `json:"isURL"`
	Email          bool `json:"isEmail"`
	Unique         bool `json:"isUnique"`
	Required       bool `json:"isRequired"`
	MinLen         int  `json:"minLen"`
	MaxLen         int  `json:"maxLen"`
	MinValue       int  `json:"minValue"`
	MaxValue       int  `json:"maxValue"`
}

type Field struct {
	Name          string           `json:"name"`
	DisplayName   string           `json:"displayName"`
	Type          Types            `json:"dataType"`
	Validator     *FieldValidation `json:"validations"`
	AutoGenerated bool             `json:"system"`
	Identity      bool             `json:"identityColumn"`
	Unique        bool             `json:"unique"`
	HideInIndex   bool             `json:"hideInIndex"`
	HideInEdit    bool             `json:"hideInEdit"`
	NeedAction    bool             `json:"needAction"`
}

func NewField() *Field {
	return &Field{Validator: &FieldValidation{}}
}
